export enum USER_GENDER {
  MALE = 'MALE',
  FEMALE = 'FEMALE',
  OTHER = 'OTHER',
}

export enum USER_ROLE {
  SUPER_ADMIN = 'SUPER_ADMIN',
  ARTIST_MANAGER = 'ARTIST_MANAGER',
  ARTIST = 'ARTIST',
}
